---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          reposieory: nginx
          tag: stable
          pullPolicy: IfNotPresent

service:
  main:
    controller: main
    ports:
      http:
        port: 80
