apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: <APP_NAME>
  namespace: <NS_NAME>
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: <APP_NAME>-helm-values
      valuesKey: values.yaml
